version: '3.2'

services:
  database:
    container_name: wp_plugin_database
    image: mysql:${MYSQL_VERSION:-5.7}
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    ports:
    - ${MYSQL_PORT:-33060}:3306

  wordpress:
    container_name: wp_plugin_wordpress
    image: wordpress:${WP_VERSION:-5.9}-apache
    links:
      - database
    ports:
      - ${WEB_PORT:-6969}:80
    volumes:
      - .:/var/www/html/wp-content/plugins/woocommerce-gateway-placetopay
      - ./tmp:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: "on"
    depends_on:
      - database
